config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'homes#index'
  resources :rooms, only: %i[index new create edit update destroy] do
    collection do
      get :search
      get :pops
      get :rock
      get :dance
      get :jazz
      get :raten
      get :classic
      get :march
      get :world
      get :vocal_music
      get :japanese_music
      get :a_cappella
    end
    member do
      get :join
    end
    resources :messages, only: %i[index create]
    resource :favorites, only: %i[create destroy]
  end
  resources :users, only: %i[show edit update] do
    get :favorites, on: :collection
  end
  resources :inquiries, only: [:index]
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_one_attached :image

  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    image.attached?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[index create]

  def index
    @user = @room.user_id
    @messages = @room.messages.includes(:user).order(:id)
    @message = current_user.messages.build
  end

  def create
    @message = Message.create!(message_params)
    if @message.save
      ActionCable.server.broadcast 'message_channel', content: @message, time: @message.created_at.strftime('%Y/%m/%d %H:%M:%S')
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id, room_id: params[:room_id])
  end

  def set_message
    @room = Room.find(params[:room_id])
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<div class="chat-room">
  <div class="chat_header">
    <div class="chat_room_name">
      <%= @room.artist_name %><p>Room</p>
    </div>
    <% if current_user.id == @user %>
    <div class="chat_end_btn">
      <%= link_to "ルーム編集", edit_room_path(@room), class: "back-info" %>
      <%= link_to "ルーム削除", room_path(@room), method: :delete, class: "back-info" %>
      <%= link_to "一覧ページへ", rooms_path, class: "back-info" %>
    </div>
    <% else %>
    <div class="chat_end_btn">
      <%= link_to "一覧ページに戻る", rooms_path, class: "back-info" %>
    </div>
    <% end %>
  </div>
  <div class="messages" id="messages" style="background-image: url('<%= rails_blob_url(@room.image) %>');">
    <%= render partial: 'shared/message' %>
  </div>
  <%= form_with model: [@room, @message], method: :post, id: "message_form" do |f| %>
    <div class="input_form">
      <%= f.text_field :content, class: 'form_message', rows: '1', id: "content", placeholder: 'メッセージを送りましょう！' %>
      <%# <label>
        <span class="glyphicon glyphicon-picture message-picture"></span>
        <%= f.file_field :image, class: 'hidden' %>
      <%# </label> %>
      <%= f.submit '送信', class: 'send_btn', id: "submit" %>
      <%= f.text_field id = "current_user_id", value: current_user.id, class: "hidden" %>
      <%= f.text_field id = "current_user_nickname", value: current_user.nickname, class: "hidden" %>
    </div>
  <% end %>
</div>