config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'homes#index'
  resources :rooms, only: %i[index new create edit update destroy] do
    collection do
      get :search
      get :pops
      get :rock
      get :dance
      get :jazz
      get :raten
      get :classic
      get :march
      get :world
      get :vocal_music
      get :japanese_music
      get :a_cappella
    end
    member do
      get :join
    end
    resources :messages, only: %i[index create]
    resource :favorites, only: %i[create destroy]
  end
  resources :users, only: %i[show edit update] do
    get :favorites, on: :collection
  end
  resources :inquiries, only: [:index]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates_uniqueness_of :room_id, scope: :user_id
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_room, only: %i[create destroy]
  before_action :authenticate_user!

  def create
    @favorite = current_user.favorites.create(room_id: params[:room_id])
  end

  def destroy
    @favorite = current_user.favorites.find_by(room_id: @room.id)
    @favorite.destroy
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if current_user.already_favorited?(room) %>
  <%= link_to room_favorites_path(room), method: :delete, remote: true do %>
    <i class="glyphicon glyphicon-heart" style="color: red;"></i>
  <% end %>
  <span style="color: red;"><%= room.favorites.count %></span>
<% else %>
  <%= link_to room_favorites_path(room), method: :post, remote: true do %>
    <i class="glyphicon glyphicon-heart"></i>
  <% end %>
  <%= room.favorites.count %>
<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @room.id %>').html("<%= j(render 'favorites/favorite', room: @room) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @room.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {room: @room}) %>");