config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'homes#index'
  resources :rooms, only: %i[index new create edit update destroy] do
    collection do
      get :search
      get :pops
      get :rock
      get :dance
      get :jazz
      get :raten
      get :classic
      get :march
      get :world
      get :vocal_music
      get :japanese_music
      get :a_cappella
    end
    member do
      get :join
    end
    resources :messages, only: %i[index create]
    resource :favorites, only: %i[create destroy]
  end
  resources :users, only: %i[show edit update] do
    get :favorites, on: :collection
  end
  resources :inquiries, only: [:index]
end

app/views/shared/_artist_list.html.erb
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">
    <div class="Artist"><%= room.artist_name %></div>
    <%= image_tag room.image, class: "room-img" if room.image.attached?  %>
    <p><%= room.genre.name %></p>
    <div class="caption">
      <%= link_to 'チャットに参加', join_room_path(room), class: "btn btn-primary", role: "button" %>
      <div id="favorites_buttons_<%= room.id %>" class="favorite">
        <%= render 'favorites/favorite', room: room %>
      </div>
    </div>
  </div>
</div>
<% unless room.present? %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag "sample.jpg", class: "room-img" %>
      <div class="caption">
        <h3>好きなアーティストのチャットを作ろう！</h3>
        <%= link_to 'アーティストを投稿する', new_room_path, class: "btn btn-primary", role: "button" %>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag "sample.jpg", class: "room-img" %>
      <div class="caption">
        <h3>チャットに参加して皆で語り合おう！</h3>
        <%= link_to 'アーティストを投稿する', new_room_path, class: "btn btn-primary", role: "button" %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= bootstrap_alert(key) %>">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong><%= value %></strong>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar-dark">
  <div class="container-fluid">
    <div class="navbar-header">
    <% if user_signed_in? %>
      <a class="navbar-brand" href="/rooms">Arti<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>Cle</a>
    <% else %>
      <a class="navbar-brand" href="/">Arti<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>Cle</a>
    <% end %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %> 
      <ul class="nav navbar-nav">
        <li><%= link_to 'お問い合わせ', inquiries_path, class: "inquiry" %></li>
        <li><%= link_to 'New Post', new_room_path, class: "NewPost" %></li>
        <%= form_with(url: search_rooms_path, local: true, method: :get, class: "navbar-form navbar-left") do |form| %>
          <%= form.text_field :keyword, placeholder: "Search", class: "input-sm form-control" %>
        <% end %>
      </ul>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %> 
        <li><%= link_to current_user.nickname, user_path(current_user.id), class: "UserName" %></li>
        <li><%= link_to 'LogOut', destroy_user_session_path, method: :delete, class: "LogOut" %></li>
      <% else %>
        <li><%= link_to 'Log In', new_user_session_path, class: "LogIn" %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path, class: "SignUp" %></li>
        <li><%= link_to 'Guest User', users_guest_sign_in_path, method: :post, class:"GuestUser" %></li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_message.html.erb
<div class="message" id="message">
<% @messages.each do |message| %>
  <% if current_user.id == message.user_id %>
  <div class="my-content" id="message">
    <div class="my-message">
      <div class="my-message-date">
        <%= l message.created_at %>
      </div>
      <div class="my-message-content" >
        <%= simple_format(h message.content) %>
      </div>
      <%# <%= image_tag message.image.variant(resize: '500x500'), class: 'my-message-image' if message.image.attached? %>
    </div>
  </div>
  <% else %>
  <div class="content" id="message">
    <div class="upper-message">
      <div class="message-user">
        <%= message.user.nickname %>
      </div>
    </div>
    <div class="lower-message">
      <div class="message-content" >
        <%= simple_format(h message.content) %>
      </div>
      <div class="message-date">
        <%= l message.created_at %>
      </div>
      <%# <%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %>
    </div>
  </div>
  <% end %>
<% end %>
</div>

app/views/shared/_ranking.html.erb
<div class="page-header">Artist Ranking</div>
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="#">総合ランキング</a></li>
  <li role="presentation" class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown" href="" role="button" aria-haspopup="true" aria-expanded="false">
    ジャンル別 ランキング <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li><a href="#">ポップス</a></li>
    <li><a href="#">ロック</a></li>
    <li><a href="#">ダンス</a></li>
    <li><a href="#">ジャズ</a></li>
    <li><a href="#">ラテン</a></li>
    <li><a href="#">クラシック</a></li>
    <li><a href="#">行進曲</a></li>
    <li><a href="#">ワールド</a></li>
    <li><a href="#">声楽</a></li>
    <li><a href="#">邦楽</a></li>
    <li><a href="#">ア・カペラ</a></li>
  </ul>
  </li>
</ul>
<div class="row">
<% if all_ranks.present? %>
  <div class="ranking">
    <div class="num_one">
      <%= image_tag 'No.1.png' %>
      <span class="one">No.1</span>
    </div>
    <div class="num_two">
      <%= image_tag 'No.2.png' %>
      <span class="two">No.2</span>
    </div>
    <div class="num_three">
      <%= image_tag 'No.3.png' %>
      <span class="three">No.3</span>
    </div>
  </div>
  <% all_ranks.each do |room| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <div class="Artist"><%= room.artist_name %></div>
        <%= image_tag room.image, class: "room-img" if room.image.attached?  %>
        <p><%= room.genre.name %></p>
        <div class="caption">
          <%= link_to 'チャットに参加', join_room_path(room), class: "btn btn-primary", role: "button" %>
          <div id="favorites_buttons_<%= room.id %>" class="favorite">
            <%= render 'favorites/favorite', room: room %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="ranking">
    <div class="num_one">
      <%= image_tag 'No.1.png' %>
      <span class="one">No.1</span>
    </div>
    <div class="num_two">
      <%= image_tag 'No.2.png' %>
      <span class="two">No.2</span>
    </div>
    <div class="num_three">
      <%= image_tag 'No.3.png' %>
      <span class="three">No.3</span>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="Artist">Aqua Timez</div>
      <%= image_tag "sample.jpg", class: "room-img" %>
      <div class="caption">
        <p>ジャンル名</p>
        <%= link_to 'チャットに参加', '#', class: "btn btn-primary", role: "button" %>
        <%= link_to '', '#', class: "glyphicon glyphicon-heart", role: "button" %>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="Artist">SUPER BEAVER</div>
      <%= image_tag "sample.jpg", class: "room-img" %>
      <div class="caption">
        <p>ジャンル名</p>
        <%= link_to 'チャットに参加', '#', class: "btn btn-primary", role: "button" %>
        <%= link_to '', '#', class: "glyphicon glyphicon-heart", role: "button" %>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="Artist">UVERworld</div>
      <%= image_tag "sample.jpg", class: "room-img" %>
      <div class="caption">
        <p>ジャンル名</p>
        <%= link_to 'チャットに参加', '#', class: "btn btn-primary", role: "button" %>
        <%= link_to '', '#', class: "glyphicon glyphicon-heart", role: "button" %>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/shared/_ranking_header.html.erb
<div class="page-header">Artist Ranking</div>
<ul class="nav nav-tabs">
  <li role="presentation"><%= link_to '総合ランキング', rooms_path, class:"nav-link active" %></li>
  <li role="presentation" class="nav-link dropdown">
  <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
    ジャンル別 ランキング <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to 'ポップス', pops_rooms_path %></li>
    <li><%= link_to 'ロック', rock_rooms_path %></li>
    <li><%= link_to 'ダンス', dance_rooms_path %></li>
    <li><%= link_to 'ジャズ', jazz_rooms_path %></li>
    <li><%= link_to 'ラテン', raten_rooms_path %></li>
    <li><%= link_to 'クラシック', classic_rooms_path %></li>
    <li><%= link_to '行進曲', march_rooms_path %></li>
    <li><%= link_to 'ワールド', world_rooms_path %></li>
    <li><%= link_to '声楽', vocal_music_rooms_path %></li>
    <li><%= link_to '邦楽', japanese_music_rooms_path %></li>
    <li><%= link_to 'ア・カペラ', a_cappella_rooms_path %></li>
  </ul>
  </li>
</ul>

app/views/shared/_rooms.html.erb
<div class="container-fluid">
  <div class="jumbotron">
    <h1>Arti<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>Cle</h1>
    <p>...</p>
    <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
  </div>
</div>

<%# アーティストランキングの表示 %>
<%= render 'shared/ranking', all_ranks: @all_ranks %>

<%# 投稿したアーティストを表示 %>
<%= render 'shared/artist_list', rooms: @rooms %>

<%# ページネーション %>
<%= paginate @rooms %>